def failing_func():
    raise TypeError
